blog/urls.py
from django.urls import include, re_path

from . import views

app_name = "blog"

urlpatterns = [
    re_path(r"^tag/(?P<tag>[-\w]+)/", views.tag_view, name="tag"),
    re_path(
        r"^category/(?P<category>[-\w]+)/feed/$",
        views.LatestCategoryFeed(),
        name="category_feed",
    ),
    re_path(r"^category/(?P<category>[-\w]+)/", views.category_view, name="category"),
    re_path(r"^author/(?P<author>[-\w]+)/", views.author_view, name="author"),
    re_path(
        r"(?P<blog_slug>[\w-]+)/rss.*/",
        views.LatestEntriesFeed(),
        name="latest_entries_feed",
    ),
    re_path(
        r"(?P<blog_slug>[\w-]+)/atom.*/",
        views.LatestEntriesFeedAtom(),
        name="latest_entries_feed_atom",
    ),
]

blog/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
from taggit.models import Tag
from wagtail.snippets.models import register_snippet

from .abstract import (
    BlogCategoryAbstract,
    BlogCategoryBlogPageAbstract,
    BlogIndexPageAbstract,
    BlogPageAbstract,
    BlogPageTagAbstract,
)

COMMENTS_APP = getattr(settings, "COMMENTS_APP", None)


class BlogIndexPage(BlogIndexPageAbstract):
    class Meta:
        verbose_name = _("Blog index")

    @property
    def blogs(self):
        # Get list of blog pages that are descendants of this page
        blogs = BlogPage.objects.descendant_of(self).live()
        blogs = (
            blogs.order_by("-date")
            .select_related("owner")
            .prefetch_related(
                "tagged_items__tag",
                "categories",
                "categories__category",
            )
        )
        return blogs

    def get_context(self, request, tag=None, category=None, author=None, *args, **kwargs):
        context = super(BlogIndexPage, self).get_context(request, *args, **kwargs)
        blogs = self.blogs

        if tag is None:
            tag = request.GET.get("tag")
        if tag:
            blogs = blogs.filter(tags__slug=tag)
        if category is None:  # Not coming from category_view in views.py
            if request.GET.get("category"):
                category = get_object_or_404(BlogCategory, slug=request.GET.get("category"))
        if category:
            if not request.GET.get("category"):
                category = get_object_or_404(BlogCategory, slug=category)
            blogs = blogs.filter(categories__category__name=category)
        if author:
            if isinstance(author, str) and not author.isdigit():
                blogs = blogs.filter(author__username=author)
            else:
                blogs = blogs.filter(author_id=author)

        # Pagination
        page = request.GET.get("page")
        page_size = 10
        if hasattr(settings, "BLOG_PAGINATION_PER_PAGE"):
            page_size = settings.BLOG_PAGINATION_PER_PAGE

        paginator = None
        if page_size is not None:
            paginator = Paginator(blogs, page_size)  # Show 10 blogs per page
            try:
                blogs = paginator.page(page)
            except PageNotAnInteger:
                blogs = paginator.page(1)
            except EmptyPage:
                blogs = paginator.page(paginator.num_pages)

        context["blogs"] = blogs
        context["category"] = category
        context["tag"] = tag
        context["author"] = author
        context["COMMENTS_APP"] = COMMENTS_APP
        context["paginator"] = paginator
        context = get_blog_context(context)

        from home.models import HomePage2

        homepage = HomePage2.objects.first()
        context["homepage"] = homepage

        return context

    subpage_types = ["blog.BlogPage"]


@register_snippet
class BlogCategory(BlogCategoryAbstract):
    class Meta:
        ordering = ["name"]
        verbose_name = _("Blog Category")
        verbose_name_plural = _("Blog Categories")


class BlogCategoryBlogPage(BlogCategoryBlogPageAbstract):
    class Meta:
        pass


class BlogPageTag(BlogPageTagAbstract):
    class Meta:
        pass


@register_snippet
class BlogTag(Tag):
    class Meta:
        proxy = True


def get_blog_context(context):
    """Get context data useful on all blog related pages"""
    context["authors"] = (
        get_user_model()
        .objects.filter(owned_pages__live=True, owned_pages__content_type__model="blogpage")
        .annotate(Count("owned_pages"))
        .order_by("-owned_pages__count")
    )
    context["all_categories"] = BlogCategory.objects.all()
    context["root_categories"] = (
        BlogCategory.objects.filter(
            parent=None,
        )
        .prefetch_related(
            "children",
        )
        .annotate(
            blog_count=Count("blogpage"),
        )
    )
    return context


class BlogPage(BlogPageAbstract):
    class Meta:
        verbose_name = _("Blog page")
        verbose_name_plural = _("Blog pages")

    def get_blog_index(self):
        # Find closest ancestor which is a blog index
        return self.get_ancestors().type(BlogIndexPage).last()

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request, *args, **kwargs)
        context["blogs"] = self.get_blog_index().blogindexpage.blogs
        context = get_blog_context(context)
        context["COMMENTS_APP"] = COMMENTS_APP

        from home.models import HomePage2

        homepage = HomePage2.objects.first()
        context["homepage"] = homepage
        return context

    parent_page_types = ["blog.BlogIndexPage"]

blog/views.py
from django.conf import settings
from django.contrib.syndication.views import Feed
from django.shortcuts import get_object_or_404
from django.utils.feedgenerator import Atom1Feed

from .models import BlogCategory, BlogIndexPage, BlogPage


def tag_view(request, tag):
    index = BlogIndexPage.objects.first()
    return index.serve(request, tag=tag)


def category_view(request, category):
    index = BlogIndexPage.objects.first()
    return index.serve(request, category=category)


def author_view(request, author):
    index = BlogIndexPage.objects.first()
    return index.serve(request, author=author)


class LatestEntriesFeed(Feed):
    """
    If a URL ends with "rss" try to find a matching BlogIndexPage
    and return its items.
    """

    def get_object(self, request, blog_slug):
        return get_object_or_404(BlogIndexPage, slug=blog_slug)

    def title(self, blog):
        if blog.seo_title:
            return blog.seo_title
        return blog.title

    def link(self, blog):
        return blog.full_url

    def description(self, blog):
        return blog.search_description

    def items(self, blog):
        num = getattr(settings, "BLOG_PAGINATION_PER_PAGE", 10)
        return blog.get_descendants().order_by("-first_published_at")[:num]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.specific.body

    def item_link(self, item):
        return item.full_url

    def item_pubdate(self, blog):
        return blog.first_published_at


class LatestEntriesFeedAtom(LatestEntriesFeed):
    feed_type = Atom1Feed


class LatestCategoryFeed(Feed):
    description = "A Blog"

    def title(self, category):
        return "Blog: " + category.name

    def link(self, category):
        return "/blog/category/" + category.slug

    def get_object(self, request, category):
        return get_object_or_404(BlogCategory, slug=category)

    def items(self, obj):
        return BlogPage.objects.filter(categories__category=obj).order_by("-date")[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static i18n wagtailcore_tags  wagtailimages_tags plausible_wagtail %}
<html>
    <head>
        <title>{{ page.title }}</title>
        {% include "home/header_assets.html" %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/tiny-slider.css">
        <meta property="og:site_name" content="StreetNoise Orchestra"/>
        <meta property="og:type" content="website"/>
        <meta property="og:title" content="{% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}"/>
        <meta property="og:url" content="{{ request.build_absolute_uri }}"/>
        <meta property="twitter:site" content="@StreetNoiseIBK"/>
        <meta property="twitter:creator" content="@StreetNoiseIBK"/>

{% block head_meta %}
        <meta property="og:description" content="{% if self.search_description %}{{ self.search_description }}{% endif %}"/>
        <meta name="twitter:card" content="summary" />
        {% if self.feed_image %}
        {% image self.feed_image width-1200 as img %}
        <meta property="og:image" content="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ img.url }}"/>
        <meta property="og:image:width" content="{{ img.width }}" />
        <meta property="og:image:height" content="{{ img.height }}" />
        {% endif %}
{% endblock %}

    </head>
    <body>
        {% include 'home/navigation.html' %}

        {% block content %}{% endblock %}

        {% include 'home/footer.html' %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/tiny-slider/2.9.2/min/tiny-slider.js"></script>
        <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>
        <script type="module" src="{% static 'js/streetnoise.js' %}"></script>
        {% block extra_js %}{% endblock %}
        {% plausible %}
    </body>

</html>

blog/templates/blog/blog_index_page.html
{% extends "blog/base.html" %}
{% load wagtailcore_tags wagtailimages_tags static i18n%}

{% block content %}
{% image page.feed_image fill-1908x216 as header_image %}
<section id="intro-header" style="background-image: url('{{header_image.url}}')">
</section>

<div class="news-category-menu">
    <ul class="container is-flex is-size-4-desktop is-size-5-mobile">
        <li class="{% if not category %}current{% endif %}">
            <a href="{% if not category %}{% pageurl page %}{% else %}{% pageurl page %}{% endif %}" title="All">All</a>
        </li>
        {% for a_category in root_categories %}
        <li class="{% if a_category == category %}current{% endif %}">
            <a href="{% url 'blog:category' a_category.slug %}" title="{{ a_category.name }}">{{ a_category.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-8"">
                {% for blog in blogs|slice:":1" %}
                <a href="{% pageurl blog %}">
                    <picture class="image is-4by3">
                        {% if blog.thumbnail_image %}
                            {% image blog.thumbnail_image fill-1000x750 format-webp as webp %}
                        {% else %}
                            {% image blog.header_image fill-1000x750 format-webp as webp %}
                        {% endif %}
                        <source srcset="{{ webp.url }}" type="image/webp">
                        {% if blog.thumbnail_image %}
                            {% image blog.thumbnail_image fill-1000x750 %}
                        {% else %}
                            {% image blog.header_image fill-1000x750 %}
                        {% endif %}
                    </picture>
                </a>

                <div class="card-content is-paddingless">
                    <div class="card-post-header">
                        <h4 class="news-post-meta">
                            <span class="news-post-category">
                                {% if blog.categories.all %}
                                {% for cat in blog.categories.all %}
                                <a itemprop="keywords" href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                                {% endif %}
                            </span>
                            <span class="is-uppercase news-post-date" itemprop="datePublished">{{ blog.date|date:"F jS, Y" }}</span>
                        </h4>
                        <h1 class="title is-2" itemprop="name headline"><a href="{% pageurl blog %}">{{ blog.title }}</a></h1>
                    </div>
                    <div class="content">
                        <p>
                            {{ blog.intro|richtext|truncatewords_html:25}}
                        </p>
                        <p class="has-text-right">
                            <a href="{% pageurl blog %}" class="is-uppercase" itemprop="url">Read More</a>
                        </p>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="column is-4-desktop is-12-tablet">
                <div class="news-sidebar">
                    <div class="is-flex-centered">
                        <div class="news-sidebar-icon">
                            {% include 'streetnoise/svg/fire.svg' %}
                        </div>
                        <h2 class="title is-4">Hot Posts</h2>
                    </div>
                    <div class="news-list-popular">
                        {% for blog in blogs|slice:":3" %}
                        <div class="article article-popular" itemscope="itemscope" itemtype="http://schema.org/BlogPosting">
                            <div class="article-popular-headline">
                                <h4 class="title is-4">
                                    <a title="{{ blog.title }}" href="{% pageurl blog %}">
                                        <span itemprop="name headline">{{ blog.title }}</span>
                                    </a>
                                </h4>
                            </div>
                            <div class="article-popular-text has-text-grey" itemprop="description">
                                {{ blog.intro|richtext|truncatewords_html:25}}
                            </div>
                            <div class="article-popular-more has-text-right">
                                <a class="more" title="{{ blog.title }}" href="{% pageurl blog %}" itemprop="url">Read more</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    </div>
</section>


{% comment %}
{% include 'home/newsletter.html' %}
{% endcomment %}
<section class="section">
    <div class="container">
        {% include "blog/blog_tile_list.html" with blogs=blogs %}
    </div>
</section>

{% endblock %}

blog/templates/blog/blog_page.html
{% extends "blog/base.html" %}

{% load wagtailcore_tags wagtailimages_tags static i18n %}

{% block head_meta %}
<meta property="og:type" content="article"/>
<meta property="og:article:published_time" content="{{ blog.date | date:'c'  }}"/>
<meta property="og:article:modified_time" content="{{ blog.last_published_at | date:'c'  }}"/>
{% if blog.categories.all %}<meta property="og:article:section" content="{{ blog.categories.first.category.name }}"/>{% endif %}
{% for tag in blog.tags.all %}<meta property="og:article:tag" content="{{ tag }}"/>
{% endfor %}
        <meta name="twitter:card" content="summary" />
        <meta property="og:description" content="{% if self.search_description %}{{ self.search_description }}{% else %}{{ blog.intro }}{% endif %}"/>
        {% if self.feed_image %}
        {% image self.feed_image width-1200 as img %}
        <meta property="og:image" content="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ img.url }}"/>
        <meta property="og:image:width" content="{{ img.width }}" />
        <meta property="og:image:height" content="{{ img.height }}" />
        {% elif blog.header_image %}
        {% image blog.header_image width-1200 as img %}
        <meta property="og:image" content="{% if request.is_secure %}https://{% else %}http://{% endif %}{{ request.get_host }}{{ img.url }}"/>
        <meta property="og:image:width" content="{{ img.width }}" />
        <meta property="og:image:height" content="{{ img.height }}" />
        {% endif %}

{% endblock %}

{% block content %}
    {% include 'blog/blog_post.html' with blog=self %}
    {% if COMMENTS_APP == 'django_comments_xtd' %}
        {% include 'blog/blog_post_comments_xtd.html' with blog=self %}
    {% endif %}

<section class="section">
    <div class="container">
        <div class="level">
            <h1 class="title">
                {% translate "More News" %}
            </h1>
        </div>
        {% include "blog/blog_tile_list.html" with blogs=blogs %}
    </div>
</section>
{% include 'home/home_cta.html' %}


{% endblock %}

blog/templates/blog/blog_post.html
{% load wagtailcore_tags wagtailimages_tags static app_tags %}
{% if blog.extra_css %}
<style type="text/css">
{{ blog.extra_css }}
</style>
{% endif  %}

<div class="news-single" itemscope="itemscope" itemtype="http://schema.org/BlogPosting">
    <section class="hero is-halfheight is-primary has-background {% if not blog.hide_header_overlay %}with-overlay{% endif %}">
        {% image blog.header_image fill-1908x700 class="hero-background is-transparent"%}
        <div class="hero-body is-relative">

            {% if not blog.hide_header_title %}
            <div style="" class="header-title-box">
                <h1 class="title has-text-centered" itemprop="headline">
                    {{ blog.title }}
                </h1>
            </div>
            {% endif %}
        </div>
    </section>
    <section class="section is-small">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-one-quarter is-half">
                    <div class="news-single-intro">
                        <h4 class="news-post-meta">
                            <span class="news-post-category">
                                {% if blog.categories.all %}
                                {% for cat in blog.categories.all %}
                                <a itemprop="keywords" href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                                {% endif %}
                            </span>

                            <time class="news-post-date" itemprop="datePublished" datetime="{{ blog.date|date:"Y-m-d" }}">
                                {{ blog.date|date:"F jS, Y" }}
                            </time>
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% for block in self.body %}
    {% if block.block_type == 'image_carousel' %}
    <section class="block-{{ block.block_type }}">
        {% include_block block %}
    </section>

    {% elif block.block_type == 'embedded_video' %}
    <section class="section-is-small">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-one-quarter is-half">
                    <div class="block-{{ block.block_type }}">
                            {% include_block block %}
                        </figure>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% else %}
    <section class="section is-small">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-one-quarter is-half">
                    <div class="news-body">
                        {% if block.block_type == 'heading' %}
                        <h2 class="content title is-size-2">{{ block.value }}</h2>
                        {% elif block.block_type == 'imagetile2' %}
                        <section class="block-{{ block.block_type }}">
                            {% include_block block with block_id=block.id|replace_dashes %}
                        </section>
                        {% else %}
                        <section class="block-{{ block.block_type }} content">
                            {% include_block block with block_id=block.id|replace_dashes %}
                        </section>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    {% endfor %}
    <section class="section">
        <div class="container">
            <div class="columns">
                {% if not blog.hide_author %}
                <div class="column is-offset-one-quarter is-half news-post-footer">
                    <p class="has-text-weight-bold news-post-signoff">Mit groovigen Grüßen,</p>
                    {% if blog.author  %}
                    <p class="news-post-author">{{ blog.author }} // SNO</p>
                    {% else %}
                    <p class="news-post-author">SNO</p>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </section>
</div>

blog/templates/blog/blog_post_comments_xtd.html
{% load comments %}

{% render_comment_list for self %}
{% render_comment_form for self %}

blog/templates/blog/blog_post_comments_xtd_link.html
{% load wagtailcore_tags comments %}

{% get_comment_count for blog as comment_count %}
<p>
    <a href="{% pageurl blog %}#comments">
        {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
    {{ comment_count|pluralize:"has,have" }} been posted.
</p>

blog/templates/blog/blog_tile_list.html
{% load wagtailcore_tags wagtailimages_tags static %}
<div class="columns">
    <div class="column">
        {% if blogs %}
        <div class="card-posts columns is-multiline news-posts">
            {% for blog in blogs %}
            <div class="card-post-item is-blog column is-one-third" itemscope="itemscope" itemtype="http://schema.org/BlogPosting">
                <div class="card card-post is-shadowless">
                    <div class="card-image">
                        <a href="{% pageurl blog %}">
                            <picture class="image is-4by3">
                                {% if blog.thumbnail_image %}
                                    {% image blog.thumbnail_image fill-640x480 format-webp as webp%}
                                {% else %}
                                    {% image blog.header_image fill-640x480 format-webp as webp%}
                                {% endif %}
                                <source srcset="{{ webp.url }}" type="image/webp">
                                {% if blog.thumbnail_image %}
                                    {% image blog.thumbnail_image fill-640x480 %}
                                {% else %}
                                    {% image blog.header_image fill-640x480 %}
                                {% endif %}
                            </picture>
                        </a>
                    </div>
                    <div class="card-content is-paddingless">
                        <div class="card-post-header">
                            <h4 class="news-post-meta">
                                <span class="news-post-category">
                                {% if blog.categories.all %}
                                {% for cat in blog.categories.all %}
                                <a itemprop="keywords" href="{% url 'blog:category' cat.category.slug %}">{{ cat.category.name }}</a>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                                {% endif %}
                                </span>
                                <span class="is-uppercase news-post-date" itemprop="datePublished">{{ blog.date|date:"F jS, Y" }}</span>
                            </h4>
                            <h1 class="title is-3" itemprop="name headline"><a href="{% pageurl blog %}" itemprop="url">{{ blog.title }}</a></h1>
                        </div>
                        <div class="content">
                            <p>
                                {{ blog.intro|richtext|truncatewords_html:25}}
                            </p>
                            <p class="has-text-right">
                                <a href="{% pageurl blog %}" class="is-uppercase">Read More</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            <ul class="pager">
                {% if blogs.has_next %}
                <li class="previous"><a href="?page={{ blogs.next_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&amp;{{ key }}={{ value }}{% endif %}{% endfor %}">&larr; Older</a></li>
                {% endif %}
                {% if blogs.has_previous %}
                <li class="next"><a href="?page={{ blogs.previous_page_number }}{% for key,value in request.GET.items %}{% if key != 'page' %}&amp;{{ key }}={{ value }}{% endif %}{% endfor %}">Newer &rarr;</a></li>
                {% endif %}
            </ul>

        </div>

        {% else %}
        <p>There are currently no blog posts</p>
        {% endif %}
    </div>
</div>